package com.example.notification_service.entity;
public enum NotificationType {
    TRANSACTION_SUCCESS,
    TRANSACTION_FAILED,
    HIGH_VALUE_TRANSACTION,
    SUSPICIOUS_ACTIVITY,
    ACCOUNT_BALANCE_LOW,
    ACCOUNT_BALANCE_CRITICAL,
    FRAUD_ALERT,
    PAYMENT_REMINDER,
    ACCOUNT_LOCKED,
    LOGIN_ALERT,
    PASSWORD_CHANGED,
    TRANSFER_RECEIVED,
    TRANSFER_SENT,
    DIRECT_DEBIT,
    STANDING_ORDER,
    CARD_TRANSACTION,
    ATM_WITHDRAWAL,
    ONLINE_PURCHASE,
    MOBILE_PAYMENT,
    INTERNATIONAL_TRANSACTION
}