server:
  port: 8081

spring:
  application:
    name: account-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/accountdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root      # change if needed
    password: password  # change accordingly
  jpa:
    hibernate:
      ddl-auto: update  # auto-create/update tables
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: account-service-group
      auto-offset-reset: latest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.example.accountservice.event,com.example.transaction_service.event"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Swagger/OpenAPI Configuration

    enabled: true
    operationsSorter: method
    tagsSorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info
    operationsSorter: method