server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    # Eureka server does not register itself with another registry
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info